name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and Test Client
        working-directory: ./client
        run: |
          npm install
          npm run test

      - name: create env file
        run: |
          touch .env
          echo MONGODB_URI=${{ secrets.MONGODB_URI }} >> .env
          echo TOKEN_KEY=${{ secrets.TOKEN_KEY }} >> .env
          echo EMAIL=${{ secrets.EMAIL }} >> .env
          echo PASSWORD=${{ secrets.PASSWORD }} >> .env

      - name: Install and Test Server
        working-directory: ./server
        run: |
          npm install
          npm run test

      - name: Build Client Docker Image
        working-directory: ./client
        run: |
          docker build -t rakeshpotnuru/productivity-app:client .

      - name: Build Server Docker Image
        working-directory: ./server
        run: |
          docker build -t rakeshpotnuru/productivity-app:server .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Images to Docker Hub
        run: |
          docker push rakeshpotnuru/productivity-app:client
          docker push rakeshpotnuru/productivity-app:server
