name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  TOKEN_KEY: ${{ secrets.TOKEN_KEY }}
  EMAIL: ${{ secrets.EMAIL }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and Test Client
        working-directory: ./client
        run: |
          npm install
          npm run test

      - name: Install and Test Server
        working-directory: ./server
        run: |
          npm install
          export MONGODB_URI=$MONGODB_URI
          export TOKEN_KEY=$TOKEN_KEY
          export EMAIL=$EMAIL
          export PASSWORD=$PASSWORD
          npm run test

      - name: Build Client Docker Image
        working-directory: ./client
        run: |
          docker build -t rakeshpotnuru/productivity-app:client .

      - name: Build Server Docker Image
        working-directory: ./server
        run: |
          docker build -t rakeshpotnuru/productivity-app:server .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Images to Docker Hub
        run: |
          docker push rakeshpotnuru/productivity-app:client
          docker push rakeshpotnuru/productivity-app:server
